/// <reference types="@sveltejs/kit" />
/// <reference lib="webworker" />

declare let self: ServiceWorkerGlobalScope;

import { build, files, version } from '$service-worker';

// Create a unique cache name using the SvelteKit deployment version
const CACHE_NAME = `offline-cache-${version}`;

// Create an array of all the files we want to cache
const ASSETS = [
	...build, // The app itself (JS/CSS generated by SvelteKit)
	...files, // Everything in your static/ directory (images, fonts, manifest)
	'/'       // The root HTML file (crucial for SPA offline routing)
];

// 1. INSTALL: Cache all assets
self.addEventListener('install', (event) => {
	// Wait until all assets are downloaded and cached before finishing install
	event.waitUntil(
		caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
	);
	
	// Force the waiting service worker to become the active service worker
	self.skipWaiting();
});

// 2. ACTIVATE: Delete old caches
self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then((keys) => {
			return Promise.all(
				keys.map((key) => {
					// Delete any cache that doesn't match our current version
					if (key !== CACHE_NAME) {
						return caches.delete(key);
					}
				})
			);
		})
	);
	
	// Take control of all pages immediately
	self.clients.claim();
});

// 3. FETCH: Serve from cache first, fall back to network (Offline-First Strategy)
self.addEventListener('fetch', (event) => {
	// Ignore non-GET requests (like POST, PUT)
	if (event.request.method !== 'GET') return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);
			
			// Try to find the requested resource in the cache
			const cachedResponse = await cache.match(event.request);
			if (cachedResponse) {
				return cachedResponse;
			}

			// If not in cache, try to fetch from the network
			try {
				const networkResponse = await fetch(event.request);
				
				// Optional: Cache new requests on the fly (useful for external assets/API data)
				// if (networkResponse.ok) {
				// 	cache.put(event.request, networkResponse.clone());
				// }
				
				return networkResponse;
			} catch (error) {
				// If offline and not in cache, return the SPA fallback shell (if applicable)
				// For a strict SPA, returning the root '/' HTML handles offline routing
				if (event.request.mode === 'navigate') {
					const fallback = await cache.match('/');
					if (fallback) return fallback;
				}
				
				throw error;
			}
		})()
	);
});